<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="394456" started-at="2019-09-17T22:20:47Z" finished-at="2019-09-17T22:27:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="394456" started-at="2019-09-17T22:20:47Z" finished-at="2019-09-17T22:27:22Z">
      <class name="kz.olx.runTest">
        <test-method status="PASS" signature="launchApp()[pri:0, instance:kz.olx.runTest@6e1ec318]" name="launchApp" is-config="true" duration-ms="16962" started-at="2019-09-17T22:20:47Z" finished-at="2019-09-17T22:21:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method status="FAIL" signature="startTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:kz.olx.runTest@6e1ec318]" name="startTest" duration-ms="143512" started-at="2019-09-17T22:21:04Z" data-provider="getCsvData" finished-at="2019-09-17T22:23:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[77079154354]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[KNF8KBMK]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[cat1]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Алматы, Ауэзовский район]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[sell iPhone in excellent condition, under warranty]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[100000]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Iphone x]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[кирил]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[tregfjfj@mail.ru]]>
              </value>
            </param>
            <param index="9">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Please find the attachment for the issue.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Please find the attachment for the issue.
at org.testng.Assert.fail(Assert.java:96)
at kz.olx.runTest.startTest(runTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method status="FAIL" signature="startTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:kz.olx.runTest@6e1ec318]" name="startTest" duration-ms="231529" started-at="2019-09-17T22:23:28Z" data-provider="getCsvData" finished-at="2019-09-17T22:27:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[77767517078]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[AKPEPT37]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[cat2]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Алматы, Акмалинский район]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[sell Samsung in excellent condition, under warranty]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[100000]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Samsung]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[кирил]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[tregfjfj@mail.ru]]>
              </value>
            </param>
            <param index="9">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Please find the attachment for the issue.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Please find the attachment for the issue.
at org.testng.Assert.fail(Assert.java:96)
at kz.olx.runTest.startTest(runTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:kz.olx.runTest@6e1ec318]" name="closeApp" is-config="true" duration-ms="2363" started-at="2019-09-17T22:27:19Z" finished-at="2019-09-17T22:27:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- kz.olx.runTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
